account/urls.py
from . import views
from django.contrib import admin
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_view, name='logout'),
    path('login', views.login_view, name='login'),
    path('signup', views.signup_view, name='signup'),
]

library/urls.py
from . import views
from django.urls import path

app_name = 'library'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about-page'),

    path('return_book/<int:pk>', views.return_book, name='return_book'),
    path('borrow_book/<int:pk>', views.borrow_book, name='borrow_book'),
    path('show_books', views.show_books, name='show_books'),
    path('borrowed_books', views.borrowed_books, name='borrowed_books'),


    path('add_book', views.add_book, name='add_book'),
    path('written_books', views.written_books, name='written_books'),
    path('edit_book/<int:pk>', views.edit_book, name='edit_book'),
    path('delete_book/<int:pk>', views.delete_book, name='delete_book'),
]

libraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('library.urls')),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

ROLE_CHOICES = (
    ("1", "Member"),
    ("2", "Author"),
)


class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    role = forms.ChoiceField(choices=ROLE_CHOICES)

    class Meta:
        model = User
        fields = ('username', 'email', 'role', 'password1', 'password2')

account/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.contrib.auth import login, logout

from library.models import Member
from .forms import SignUpForm


# Create your views here.
@login_required(login_url='accounts:login', redirect_field_name='')
def index(request):
    context = {
        'username': request.user.username,
        'email': request.user.email,
    }
    return render(request, 'accounts/index.html', context)


def signup_view(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')
    if request.method == 'POST':
        form = SignUpForm(data=request.POST or None)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            role = form.cleaned_data.get('role')
            user = authenticate(username=username, password=raw_password)
            role = 'member' if role == '1' else 'author'
            member = Member.objects.create(user=user, role=role)
            member.save()

            print(role)
            login(request, user)
            return redirect('library:index')
        else:
            form.add_error(None, 'Invalid username or password')
            print(form.errors)
            return redirect('accounts:signup')
    else:
        form = SignUpForm()
        return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect('accounts:index')

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('library:index')
            else:
                form.add_error(None, 'Invalid username or password')
                return redirect('accounts:login')
        else:
            print('not valid', form.errors)
    form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


@login_required(login_url='accounts:login', redirect_field_name='')
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('library:about-page')
    else:
        return render(request, 'accounts/logout.html', {})

templates/accounts/index.html
{% extends "base.html" %}

{% block title_block %}
	accounts detail
{% endblock %}

{% block content_block %}
    <p>
        accounts index page
    </p>
    <ul>
        <li>
            <p>
                username: {{username}}
            </p>
        </li>
        <li>
            <p>
                email: {{email}}
            </p>
        </li>
    </ul>
    
    <a href="{% url 'library:index' %}">library</a>
    <a href="{% url 'accounts:logout' %}">logout</a>
    
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title_block %}
	login to your personal account
{% endblock %}

{% block content_block %}
<form method="POST" action=""> 
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
    <a href="{% url 'accounts:signup' %}">signup</a>
</form>
{% endblock %}

templates/accounts/logout.html
{% extends "base.html" %}

{% block title_block %}
	logout page
{% endblock %}

{% block content_block %}
<form method="POST" action="">
    {% csrf_token %}
    <button type="submit">Submit</button>    
    <a href="{% url 'library:index' %}">main page</a>
</form>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}

{% block title_block %}
	sign up new members
{% endblock %}

{% block content_block %}
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>
{% endblock %}