account/urls.py
from . import views
from django.contrib import admin
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_view, name='logout'),
    path('login', views.login_view, name='login'),
    path('signup', views.signup_view, name='signup'),
]

library/urls.py
from . import views
from django.urls import path

app_name = 'library'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about-page'),

    path('return_book/<int:pk>', views.return_book, name='return_book'),
    path('borrow_book/<int:pk>', views.borrow_book, name='borrow_book'),
    path('show_books', views.show_books, name='show_books'),
    path('borrowed_books', views.borrowed_books, name='borrowed_books'),


    path('add_book', views.add_book, name='add_book'),
    path('written_books', views.written_books, name='written_books'),
    path('edit_book/<int:pk>', views.edit_book, name='edit_book'),
    path('delete_book/<int:pk>', views.delete_book, name='delete_book'),
]

libraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('library.urls')),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    membership_date = models.DateField(auto_now_add=True)
    role = models.TextField(default='member')

    def __str__(self):
        return self.user.username


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Member, on_delete=models.CASCADE)
    isbn = models.CharField(max_length=13, unique=True)
    copies = models.IntegerField(default=1)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('products:products-details', kwargs={'id': self.id})


class BorrowRecord(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    borrowed_date = models.DateField(auto_now_add=True)
    return_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.member.user.username} borrowed {self.book.title}"

library/forms.py
from django import forms
from . import models as lib_models


class BookForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    copies = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    isbn = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = lib_models.Book
        fields = ('title', 'copies', 'isbn')

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.get('instance', None)
        super().__init__(*args, **kwargs)

    def clean_title(self, *args, **kwargs):
        title = self.cleaned_data.get('title')
        books_with_same_title = lib_models.Book.objects.filter(title__iexact=title)
        if self.instance:
            books_with_same_title = books_with_same_title.exclude(pk=self.instance.pk)
        if books_with_same_title.exists():
            raise forms.ValidationError('Book with same title is already taken')
        return title

    def clean_copies(self, *args, **kwargs):
        copies = self.cleaned_data.get('copies')
        if copies > 0:
            return copies
        else:
            raise forms.ValidationError(None, 'Number of copies cannot be zero')

    def clean_isbn(self, *args, **kwargs):
        isbn = self.cleaned_data.get('isbn')
        books_with_same_isbn = lib_models.Book.objects.filter(isbn=isbn)
        if self.instance:
            books_with_same_isbn = books_with_same_isbn.exclude(pk=self.instance.pk)
        if books_with_same_isbn.exists():
            raise forms.ValidationError(None, 'Book with this ISBN already exists')
        for ch in isbn:
            if not ch.isdigit():
                raise forms.ValidationError(None, 'Invalid ISBN')
        return isbn

library/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from . import models
from .forms import BookForm
from .models import BorrowRecord, Member


# Create your views here.
def about(request):
    return render(request, 'library/about.html', {})


@login_required(login_url='accounts:login', redirect_field_name='')
def index(request):
    user = request.user
    member = Member.objects.get(user=user)
    return render(request, 'library/index.html', {'member': member})


# member views:
@login_required(login_url='accounts:login', redirect_field_name='')
def borrowed_books(request):
    user = request.user
    member = models.Member.objects.get(user=user)
    borrows = models.BorrowRecord.objects.filter(member=member, return_date=None)
    context = {'member': member, 'borrows': borrows}
    return render(request, 'library/your books.html', context)


@login_required(login_url='accounts:login', redirect_field_name='')
def show_books(request):
    available_books = models.Book.objects.filter(copies__gt=0)
    return render(request, 'library/show_books.html', {'available_books': available_books})


@login_required(login_url='accounts:login', redirect_field_name='')
def borrow_book(request, pk):
    book = get_object_or_404(models.Book, pk=pk)
    book.copies -= 1
    book.save()
    member = models.Member.objects.get(user=request.user)
    borrow = BorrowRecord(book=book, member=member,
                          return_date=None)
    borrow.save()
    return redirect('library:index')


@login_required(login_url='accounts:login', redirect_field_name='')
def return_book(request, pk):
    book = get_object_or_404(models.Book, pk=pk)
    book.copies += 1
    book.save()
    member = models.Member.objects.get(user=request.user)
    borrow = BorrowRecord.objects.filter(member=member, book=book, return_date=None)
    borrow = borrow.first()
    borrow.return_date = datetime.date.today()
    borrow.save()
    return redirect('library:index')


# author views
@login_required(login_url='accounts:login', redirect_field_name='')
def written_books(request):
    user = request.user
    member = models.Member.objects.get(user=user)
    books = models.Book.objects.filter(author=member)
    return render(request, 'library/written books.html', {'written_books': books})


@login_required(login_url='accounts:login', redirect_field_name='')
def add_book(request):
    if request.method == 'POST':
        form = BookForm(data=request.POST or None)
        if form.is_valid():
            member = models.Member.objects.get(user=request.user)
            title = form.cleaned_data['title']
            isbn = form.cleaned_data['isbn']
            copies = form.cleaned_data['copies']
            book = models.Book.objects.create(title=title, author=member, isbn=isbn, copies=copies)
            book.save()
            # form.save()
            return redirect('library:index')
        else:
            form.add_error(None, 'Invalid information')
            print(form.errors)
            return redirect('library:add_book')
    else:
        form = BookForm()
        return render(request, "library/add_book.html", {'form': form})


@login_required(login_url='accounts:login', redirect_field_name='')
def edit_book(request, pk):
    if request.method == 'POST':
        book = get_object_or_404(models.Book, pk=pk)
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('library:index')
        else:
            print(form.errors)
            return redirect('library:edit_book', pk)
    book = get_object_or_404(models.Book, pk=pk)
    form = BookForm(instance=book)
    return render(request, 'library/edit_book.html',
                  {'form': form, 'pk': pk})


@login_required(login_url='accounts:login', redirect_field_name='')
def delete_book(request, pk):
    book = get_object_or_404(models.Book, pk=pk)
    book.delete()
    return redirect('library:index')

templates/library/about.html
{% extends 'base.html' %}

{% block title_block %}
	Library management system about page
{% endblock %}

{% block content_block %}
    <h2>Library management system about page</h2>
    <p>
        this webapp aims to serve the users a free management system and private environment for managing daily tasks.
        having features such as checking a task as done, viewing done or not done tasks, deleting tasks, updating tasks
        and can store each task with its title, description, deadline date and a flag for being done status.
        built and developed by django backend framework.
    </p>
    <p>
        note that if you wish to borrow a book with an account that is signed up as a writer,
        it won't be possible, and you will have to sign up an second account as member
    </p>
    <a href="{% url 'accounts:login' %}">login to use these features</a>
{% endblock %}

templates/library/add_book.html
{% extends 'base.html' %}

{% block title_block %}
	add book
{% endblock %}

{% block content_block %}
    <form method="post" action=""> {% csrf_token %}
    	{{ form.as_p }}
        <button type="submit">submit</button>
        <a href="{% url 'library:index' %}">main page</a>
    </form>
{% endblock %}

templates/library/book_detail_customer.html
{% extends 'base.html' %}

{% block title_block %}
    book detail
{% endblock %}

{% block content_block %}
    <a href="{% url 'library:index' %}">main page</a>
    {{ form.as_table }}
{% endblock %}

templates/library/edit_book.html
{% extends 'base.html' %}

{% block title_block %}
	edit book
{% endblock %}

{% block content_block %}
    <form method="post" action="{% url 'library:edit_book' pk %}"> {% csrf_token %}
	    {{ form.as_p }}
        <button type="submit">save</button>
        <a href="{% url 'library:index' %}">main page</a>
    </form>
{% endblock %}

templates/library/index.html
{% extends 'base.html' %}

{% block title_block %}
	ToDo WebApp
{% endblock %}

{% block header_block %}
	
{% endblock %}

{% block content_block %}
	<h1>
    Library Management webapp index page
    </h1>
    
    <h2>
       choose what you're willing to do now:
    </h2>
    
    <ul>
    {% if member.role == 'member' %}
        <li>
            <p> <a href={% url 'library:show_books' %}>borrow book</a> </p>
        </li>
        <li>
            <p> <a href={% url 'library:borrowed_books' %}>your books</a> </p>
        </li>
    {% else %}
        <li>
            <p> <a href={% url 'library:add_book' %}>add book</a> </p>
        </li>
        <li>
            <p> <a href={% url 'library:written_books' %}>your books</a> </p>
        </li>
        
    {% endif %}
    
        <li>
            <p> <a href={% url 'accounts:index' %}>your account</a> </p>
        </li>
        <li>
            <p> <a href={% url 'library:about-page' %}>about the webapp</a> </p>
        </li>
    </ul>
   
    
{% endblock %}

{% block footer_block %}
	
{% endblock %}

templates/library/show_books.html
{% extends 'base.html' %}

{% block title_block %}
	available books
{% endblock %}

{% block content_block %}
    <a href="{% url 'library:index' %}">main page</a>
    <ul>
	{% for available_book in available_books %}
		<li>
            <p>
                {{ available_book.title }}  - {{ available_book.author.user.username }}
            </p>
            <form method="get" action="{% url 'library:borrow_book' available_book.pk %}"> 
                <button type="submit">Borrow</button>
            </form>
        </li>
	{% endfor %}
	</ul>
{% endblock %}

templates/library/written books.html
{% extends 'base.html' %}

{% block title_block %}
	written books
{% endblock %}

{% block content_block %}
    <h2>
        list of books you have written:
        <a href="{% url 'library:index' %}">main page</a>
    </h2>
    <ul>
	{% for book in written_books %}
		<li>
            <p>
                {{ book.title }} - {{ book.copies }}
                - 
                <a href="{% url 'library:edit_book' book.pk %}">edit</a>
                -
                <a href="{% url 'library:delete_book' book.pk %}">delete</a>
            </p>
        </li>
	{% endfor %}
	</ul>
{% endblock %}

templates/library/your books.html
{% extends 'base.html' %}

{% block title_block %}
	user profile
{% endblock %}

{% block content_block %}
	<h2>
        list of the books you have borrowed:
    <a href="{% url 'library:index' %}">main page</a>
    </h2>
    
    <ul>
        {% for borrow in borrows %}
        	<li>
                <p>
                    {{ borrow.book.title }} - {{ borrow.borrowed_date }}
                </p>
                <form method="get" action="{% url 'library:return_book' borrow.book.pk %}">
                    <button type="submit">return</button>
                </form>
            </li>
        {% endfor %}
    </ul>
{% endblock %}